<?php
/**
 * Settings language file generated by PluginLibrary.
 *
 */

$l['setting_group_simplelikes'] = "Like System Settings";
$l['setting_group_simplelikes_desc'] = "Settings for the like system.";
$l['setting_simplelikes_num_users'] = "Number of \"likers\" to show per post";
$l['setting_simplelikes_num_users_desc'] = "Set the number of most recent likers to show in the post like bar.";
$l['setting_simplelikes_can_like_own'] = "Let users like own posts?";
$l['setting_simplelikes_can_like_own_desc'] = "Set whether users can \"like\" their own posts.";
$l['setting_simplelikes_get_num_likes_user_postbit'] = "Number of likes received in postbit?";
$l['setting_simplelikes_get_num_likes_user_postbit_desc'] = "Do you wish to get how many likes a user has received in the postbit? Beware that this adds an extra query.";
